[phases.setup]
nixPkgs = ['nodejs', 'python39', 'postgresql']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'cd frontend && npm install'
]

[phases.build]
cmds = [
    'cd frontend && npm run build',
    'cp -r frontend/build app/static'
]

[start]
cmd = 'cd app && uvicorn main:app --host 0.0.0.0 --port $PORT'
